[package]
name = "zed_livelove"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/livelove.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.1.0"
